name: Run tests

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      [ master, stage ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    strategy:
      matrix:
        deploy_number: [1, 2]  # Два окремі деплої
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set env
        run: |
          echo "DEPLOY_NUMBER=${{ matrix.deploy_number }}" >> $GITHUB_ENV
          echo "env=${{ github.workflow }}-${{ github.ref }}" >> $GITHUB_ENV

      - name: Print env
        run: |
          echo "Running deploy number: $DEPLOY_NUMBER"
          echo "env after print: $env"
