name: Run tests

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      [ master, stage ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: deploy
        run: echo "Deploying to production"