name: Run tests

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      [ master, stage ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set env
        id: set-env
        run: |
          echo "${{ github.ref }}" >> $GITHUB_ENV

      - name: print env
        run: |
          echo ${{ steps.set-env.outputs.set-env }}
